unit Animate;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TForm3=class(TForm)
    tmr1: TTimer;
    OFFS_030C: N.A.;
    OFFS_030D: N.A.;
    OFFS_0324: N.A.;
    OFFS_0304: N.A.;
    procedure tmr1Timer(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure FormCanResize(Sender : TObject);
    procedure FormMouseMove(Sender : TObject);
    procedure FormMouseDown(Sender : TObject);
    procedure FormMouseUp(Sender : TObject);
    procedure FormDblClick(Sender : TObject);
    procedure ChangeLight(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form3: TForm3;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TForm3.tmr1Timer(Sender : TObject);
begin
(*
004781C8   53                     push    ebx
004781C9   51                     push    ecx
004781CA   8BD8                   mov     ebx, eax

* Reference to: System.Randomize;
|
004781CC   E817ABF8FF             call    00402CE8

* Reference to field TForm3.OFFS_030C : Byte
|
004781D1   80BB0C03000000         cmp     byte ptr [ebx+$030C], $00
004781D8   7457                   jz      00478231
004781DA   B80A000000             mov     eax, $0000000A

|
004781DF   E89CB0F8FF             call    00403280
004781E4   890424                 mov     [esp], eax
004781E7   DB0424                 fild    dword ptr [esp]
004781EA   D83568824700           fdiv    dword ptr [$00478268]
004781F0   DD1D1CEC4700           fstp    qword ptr [$0047EC1C]
004781F6   9B                     wait
004781F7   B80A000000             mov     eax, $0000000A

|
004781FC   E87FB0F8FF             call    00403280
00478201   890424                 mov     [esp], eax
00478204   DB0424                 fild    dword ptr [esp]
00478207   D83568824700           fdiv    dword ptr [$00478268]
0047820D   DD1D24EC4700           fstp    qword ptr [$0047EC24]
00478213   9B                     wait
00478214   B80A000000             mov     eax, $0000000A

|
00478219   E862B0F8FF             call    00403280
0047821E   890424                 mov     [esp], eax
00478221   DB0424                 fild    dword ptr [esp]
00478224   D83568824700           fdiv    dword ptr [$00478268]
0047822A   DD1D2CEC4700           fstp    qword ptr [$0047EC2C]
00478230   9B                     wait

* Reference to field TForm3.OFFS_030D : Byte
|
00478231   80BB0D03000000         cmp     byte ptr [ebx+$030D], $00
00478238   7424                   jz      0047825E
0047823A   B814000000             mov     eax, $00000014

|
0047823F   E83CB0F8FF             call    00403280
00478244   83C002                 add     eax, +$02

* Reference to GlobalVar_0047EC3C
|
00478247   A33CEC4700             mov     dword ptr [$0047EC3C], eax
0047824C   B814000000             mov     eax, $00000014

|
00478251   E82AB0F8FF             call    00403280
00478256   83C002                 add     eax, +$02

* Reference to GlobalVar_0047EC40
|
00478259   A340EC4700             mov     dword ptr [$0047EC40], eax
0047825E   8BC3                   mov     eax, ebx

|
00478260   E8AFEDFFFF             call    00477014
00478265   5A                     pop     edx
00478266   5B                     pop     ebx
00478267   C3                     ret

*)
end;

procedure TForm3.FormCreate(Sender : TObject);
begin
(*
0047826C   53                     push    ebx
0047826D   56                     push    esi
0047826E   57                     push    edi
0047826F   83C4E8                 add     esp, -$18
00478272   8BFA                   mov     edi, edx
00478274   8BD8                   mov     ebx, eax
00478276   33C0                   xor     eax, eax

* Reference to field TForm3.OFFS_0310
|
00478278   898310030000           mov     [ebx+$0310], eax

* Reference to field TForm3.OFFS_0308
|
0047827E   C7830803000002000000   mov     dword ptr [ebx+$0308], $00000002

* Reference to field TForm3.OFFS_0324 : Byte
|
00478288   C6832403000000         mov     byte ptr [ebx+$0324], $00
0047828F   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.GetClientWidth(TControl):Integer;
|
00478291   E81A2EFCFF             call    0043B0B0

* Reference to GlobalVar_0047ECA4
|
00478296   A3A4EC4700             mov     dword ptr [$0047ECA4], eax
0047829B   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.GetClientHeight(TControl):Integer;
|
0047829D   E8522EFCFF             call    0043B0F4

* Reference to GlobalVar_0047ECA8
|
004782A2   A3A8EC4700             mov     dword ptr [$0047ECA8], eax

* Reference to TForm2 instance
|
004782A7   A188DC4700             mov     eax, dword ptr [$0047DC88]
004782AC   8B00                   mov     eax, [eax]

* Reference to control TForm2.TrackBar1 : TTrackBar
|
004782AE   8B8004030000           mov     eax, [eax+$0304]
004782B4   BA32000000             mov     edx, $00000032

* Reference to: ComCtrls.TTrackBar.SetPosition(TTrackBar;Integer);
|
004782B9   E8727FFEFF             call    00460230

* Reference to TForm2 instance
|
004782BE   A188DC4700             mov     eax, dword ptr [$0047DC88]
004782C3   8B00                   mov     eax, [eax]
004782C5   33D2                   xor     edx, edx

* Reference to : TForm2.TrackBar1Change()
|
004782C7   E8F80B0000             call    00478EC4
004782CC   C60580EC470000         mov     byte ptr [$0047EC80], $00

* Reference to field TForm3.OFFS_0304 : Byte
|
004782D3   C6830403000000         mov     byte ptr [ebx+$0304], $00
004782DA   8BC3                   mov     eax, ebx

* Reference to: QForms.TCustomForm.GetClientHandle(TCustomForm):QWorkspaceH;
|
004782DC   E8FB9BFCFF             call    00441EDC
004782E1   50                     push    eax

* Reference to: user32.GetDC()
|
004782E2   E8BDEBF8FF             call    00406EA4
004782E7   8BF0                   mov     esi, eax

* Reference to field TForm3.OFFS_0300
|
004782E9   89B300030000           mov     [ebx+$0300], esi
004782EF   8BC6                   mov     eax, esi

|
004782F1   E81EFDFFFF             call    00478014
004782F6   84C0                   test    al, al
004782F8   7507                   jnz     00478301
004782FA   8BC3                   mov     eax, ebx

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
004782FC   E893FAFDFF             call    00457D94

* Reference to field TForm3.OFFS_0300
|
00478301   8B8300030000           mov     eax, [ebx+$0300]
00478307   50                     push    eax

* Reference to: opengl32.wglCreateContext()
|
00478308   E8E7E9F8FF             call    00406CF4

* Reference to field TForm3.OFFS_02FC
|
0047830D   8983FC020000           mov     [ebx+$02FC], eax
00478313   C60580EC470000         mov     byte ptr [$0047EC80], $00

* Reference to field TForm3.OFFS_02FC
|
0047831A   8B83FC020000           mov     eax, [ebx+$02FC]
00478320   50                     push    eax

* Reference to field TForm3.OFFS_0300
|
00478321   8B8300030000           mov     eax, [ebx+$0300]
00478327   50                     push    eax

* Reference to: opengl32.wglMakeCurrent()
|
00478328   E8D7E9F8FF             call    00406D04
0047832D   6A00                   push    $00
0047832F   6A00                   push    $00
00478331   6A00                   push    $00
00478333   6A00                   push    $00

* Reference to: opengl32.glClearColor()
|
00478335   E84AB0FEFF             call    00463384
0047833A   8BC7                   mov     eax, edi

|
0047833C   E8BBFDFFFF             call    004780FC
00478341   68570B0000             push    $00000B57

* Reference to: opengl32.glEnable()
|
00478346   E849B0FEFF             call    00463394
0047834B   68710B0000             push    $00000B71

* Reference to: opengl32.glEnable()
|
00478350   E83FB0FEFF             call    00463394
00478355   68500B0000             push    $00000B50

* Reference to: opengl32.glEnable()
|
0047835A   E835B0FEFF             call    00463394
0047835F   6801400000             push    $00004001

* Reference to: opengl32.glEnable()
|
00478364   E82BB0FEFF             call    00463394
00478369   33C0                   xor     eax, eax
0047836B   890544EC4700           mov     [$0047EC44], eax
00478371   33C0                   xor     eax, eax
00478373   890548EC4700           mov     [$0047EC48], eax
00478379   C7054CEC470000000040   mov     dword ptr [$0047EC4C], $40000000
00478383   33C0                   xor     eax, eax
00478385   890550EC4700           mov     [$0047EC50], eax
0047838B   33C0                   xor     eax, eax
0047838D   890554EC4700           mov     [$0047EC54], eax
00478393   33C0                   xor     eax, eax
00478395   890558EC4700           mov     [$0047EC58], eax
0047839B   C7055CEC4700000000C0   mov     dword ptr [$0047EC5C], $C0000000
004783A5   33C0                   xor     eax, eax
004783A7   890560EC4700           mov     [$0047EC60], eax
004783AD   33C0                   xor     eax, eax
004783AF   890424                 mov     [esp], eax
004783B2   33C0                   xor     eax, eax
004783B4   89442404               mov     [esp+$04], eax
004783B8   C7442408000000C0       mov     dword ptr [esp+$08], $C0000000
004783C0   33C0                   xor     eax, eax
004783C2   8944240C               mov     [esp+$0C], eax
004783C6   33C0                   xor     eax, eax
004783C8   89442410               mov     [esp+$10], eax
004783CC   C744241400000040       mov     dword ptr [esp+$14], $40000000

* Reference to: opengl32.glLoadIdentity()
|
004783D4   E8F3AFFEFF             call    004633CC
004783D9   6844EC4700             push    $0047EC44
004783DE   6803120000             push    $00001203
004783E3   6800400000             push    $00004000

* Reference to: opengl32.glLightfv()
|
004783E8   E8CFAFFEFF             call    004633BC
004783ED   6854EC4700             push    $0047EC54
004783F2   6803120000             push    $00001203
004783F7   6801400000             push    $00004001

* Reference to: opengl32.glLightfv()
|
004783FC   E8BBAFFEFF             call    004633BC
00478401   54                     push    esp
00478402   6804120000             push    $00001204
00478407   6800400000             push    $00004000

* Reference to: opengl32.glLightfv()
|
0047840C   E8ABAFFEFF             call    004633BC
00478411   8D44240C               lea     eax, [esp+$0C]
00478415   50                     push    eax
00478416   6804120000             push    $00001204
0047841B   6801400000             push    $00004001

* Reference to: opengl32.glLightfv()
|
00478420   E897AFFEFF             call    004633BC
00478425   68520B0000             push    $00000B52
0047842A   6803120000             push    $00001203

* Reference to: opengl32.glLightModeli()
|
0047842F   E880AFFEFF             call    004633B4
00478434   83C418                 add     esp, +$18
00478437   5F                     pop     edi
00478438   5E                     pop     esi
00478439   5B                     pop     ebx
0047843A   C3                     ret

*)
end;

procedure TForm3.FormClose(Sender : TObject);
begin
(*
0047843C   53                     push    ebx
0047843D   56                     push    esi
0047843E   8BD8                   mov     ebx, eax

* Reference to field TForm3.OFFS_0304 : Byte
|
00478440   C6830403000001         mov     byte ptr [ebx+$0304], $01

* Reference to field TForm3.OFFS_02FC
|
00478447   83BBFC02000000         cmp     dword ptr [ebx+$02FC], +$00
0047844E   741A                   jz      0047846A
00478450   6A00                   push    $00

* Reference to field TForm3.OFFS_0300
|
00478452   8B8300030000           mov     eax, [ebx+$0300]
00478458   50                     push    eax

* Reference to: opengl32.wglMakeCurrent()
|
00478459   E8A6E8F8FF             call    00406D04

* Reference to field TForm3.OFFS_02FC
|
0047845E   8B83FC020000           mov     eax, [ebx+$02FC]
00478464   50                     push    eax

* Reference to: opengl32.wglDeleteContext()
|
00478465   E892E8F8FF             call    00406CFC

* Reference to field TForm3.OFFS_0300
|
0047846A   83BB0003000000         cmp     dword ptr [ebx+$0300], +$00
00478471   7414                   jz      00478487

* Reference to field TForm3.OFFS_0300
|
00478473   8B8300030000           mov     eax, [ebx+$0300]
00478479   50                     push    eax
0047847A   8BC3                   mov     eax, ebx

* Reference to: QForms.TCustomForm.GetClientHandle(TCustomForm):QWorkspaceH;
|
0047847C   E85B9AFCFF             call    00441EDC
00478481   50                     push    eax

* Reference to: user32.ReleaseDC()
|
00478482   E86DECF8FF             call    004070F4

* Reference to Form3
|
00478487   A118EC4700             mov     eax, dword ptr [$0047EC18]
0047848C   66BEB1FF               mov     si, $FFB1

* Reference to: System.@CallDynaInst;
|
00478490   E83FB7F8FF             call    00403BD4
00478495   5E                     pop     esi
00478496   5B                     pop     ebx
00478497   C3                     ret

*)
end;

procedure TForm3.FormCanResize(Sender : TObject);
begin
(*
00478498   55                     push    ebp
00478499   8BEC                   mov     ebp, esp
0047849B   8BC2                   mov     eax, edx

|
0047849D   E85AFCFFFF             call    004780FC
004784A2   5D                     pop     ebp
004784A3   C20800                 ret     $0008

*)
end;

procedure TForm3.FormMouseMove(Sender : TObject);
begin
(*
004784A8   55                     push    ebp
004784A9   8BEC                   mov     ebp, esp
004784AB   51                     push    ecx
004784AC   53                     push    ebx
004784AD   56                     push    esi
004784AE   57                     push    edi
004784AF   8BD8                   mov     ebx, eax
004784B1   8B7D08                 mov     edi, [ebp+$08]
004784B4   8B750C                 mov     esi, [ebp+$0C]
004784B7   803D80EC470000         cmp     byte ptr [$0047EC80], $00
004784BE   7468                   jz      00478528
004784C0   8975FC                 mov     [ebp-$04], esi
004784C3   DB45FC                 fild    dword ptr [ebp-$04]
004784C6   DC2D94EC4700           fsubr   qword ptr [$0047EC94]
004784CC   DD1D84EC4700           fstp    qword ptr [$0047EC84]
004784D2   9B                     wait
004784D3   897DFC                 mov     [ebp-$04], edi
004784D6   DB45FC                 fild    dword ptr [ebp-$04]
004784D9   DC2D9CEC4700           fsubr   qword ptr [$0047EC9C]
004784DF   DD1D8CEC4700           fstp    qword ptr [$0047EC8C]
004784E5   9B                     wait

* Reference to: opengl32.glPopMatrix()
|
004784E6   E8F9AEFEFF             call    004633E4
004784EB   6A00                   push    $00
004784ED   680000803F             push    $3F800000
004784F2   6A00                   push    $00
004784F4   DD0584EC4700           fld     qword ptr [$0047EC84]
004784FA   83C4FC                 add     esp, -$04
004784FD   D91C24                 fstp    dword ptr [esp]
00478500   9B                     wait

* Reference to: opengl32.glRotatef()
|
00478501   E8F6AEFEFF             call    004633FC
00478506   6A00                   push    $00
00478508   6A00                   push    $00
0047850A   680000803F             push    $3F800000
0047850F   DD058CEC4700           fld     qword ptr [$0047EC8C]
00478515   83C4FC                 add     esp, -$04
00478518   D91C24                 fstp    dword ptr [esp]
0047851B   9B                     wait

* Reference to: opengl32.glRotatef()
|
0047851C   E8DBAEFEFF             call    004633FC
00478521   8BC3                   mov     eax, ebx

|
00478523   E8ECEAFFFF             call    00477014
00478528   8975FC                 mov     [ebp-$04], esi
0047852B   DB45FC                 fild    dword ptr [ebp-$04]
0047852E   DD1D94EC4700           fstp    qword ptr [$0047EC94]
00478534   9B                     wait
00478535   897DFC                 mov     [ebp-$04], edi
00478538   DB45FC                 fild    dword ptr [ebp-$04]
0047853B   DD1D9CEC4700           fstp    qword ptr [$0047EC9C]
00478541   9B                     wait
00478542   5F                     pop     edi
00478543   5E                     pop     esi
00478544   5B                     pop     ebx
00478545   59                     pop     ecx
00478546   5D                     pop     ebp
00478547   C20800                 ret     $0008

*)
end;

procedure TForm3.FormMouseDown(Sender : TObject);
begin
(*
0047854C   55                     push    ebp
0047854D   8BEC                   mov     ebp, esp
0047854F   C60580EC470001         mov     byte ptr [$0047EC80], $01
00478556   5D                     pop     ebp
00478557   C20C00                 ret     $000C

*)
end;

procedure TForm3.FormMouseUp(Sender : TObject);
begin
(*
0047855C   55                     push    ebp
0047855D   8BEC                   mov     ebp, esp
0047855F   C60580EC470000         mov     byte ptr [$0047EC80], $00
00478566   5D                     pop     ebp
00478567   C20C00                 ret     $000C

*)
end;

procedure TForm3.FormDblClick(Sender : TObject);
begin
(*
0047856C   55                     push    ebp
0047856D   8BEC                   mov     ebp, esp
0047856F   83C4EC                 add     esp, -$14
00478572   8945FC                 mov     [ebp-$04], eax

* Reference to: user32.GetDesktopWindow()
|
00478575   E83AE9F8FF             call    00406EB4
0047857A   8945F0                 mov     [ebp-$10], eax

* Reference to Form3
|
0047857D   8B45F0                 mov     eax, [ebp-$10]
00478580   50                     push    eax

* Reference to: user32.GetDC()
|
00478581   E81EE9F8FF             call    00406EA4
00478586   8945EC                 mov     [ebp-$14], eax
00478589   33C0                   xor     eax, eax
0047858B   55                     push    ebp
0047858C   68D7854700             push    $004785D7

***** TRY
|
00478591   64FF30                 push    dword ptr fs:[eax]
00478594   648920                 mov     fs:[eax], esp
00478597   6A08                   push    $08
00478599   8B45EC                 mov     eax, [ebp-$14]
0047859C   50                     push    eax

* Reference to: gdi32.GetDeviceCaps()
|
0047859D   E8EAE5F8FF             call    00406B8C
004785A2   8945F8                 mov     [ebp-$08], eax
004785A5   6A0A                   push    $0A
004785A7   8B45EC                 mov     eax, [ebp-$14]
004785AA   50                     push    eax

* Reference to: gdi32.GetDeviceCaps()
|
004785AB   E8DCE5F8FF             call    00406B8C
004785B0   8945F4                 mov     [ebp-$0C], eax
004785B3   33C0                   xor     eax, eax
004785B5   5A                     pop     edx
004785B6   59                     pop     ecx
004785B7   59                     pop     ecx
004785B8   648910                 mov     fs:[eax], edx

****** FINALLY
|
004785BB   68DE854700             push    $004785DE
004785C0   8B45EC                 mov     eax, [ebp-$14]
004785C3   50                     push    eax

* Reference to Form3
|
004785C4   8B45F0                 mov     eax, [ebp-$10]
004785C7   50                     push    eax

* Reference to: user32.ReleaseDC()
|
004785C8   E827EBF8FF             call    004070F4
004785CD   85C0                   test    eax, eax
004785CF   7505                   jnz     004785D6

* Reference to: SysUtils.RaiseLastOSError;
|
004785D1   E8B251F9FF             call    0040D788
004785D6   C3                     ret


* Reference to: System.@HandleFinally;
|
004785D7   E958BBF8FF             jmp     00404134
004785DC   EBE2                   jmp     004785C0

****** END
|
* Reference to Form3
|
004785DE   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Controls.TControl.GetClientHeight(TControl):Integer;
|
004785E1   E80E2BFCFF             call    0043B0F4
004785E6   3B45F4                 cmp     eax, [ebp-$0C]
004785E9   7434                   jz      0047861F
004785EB   8B55F4                 mov     edx, [ebp-$0C]

* Reference to Form3
|
004785EE   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Controls.TControl.SetHeight(TControl;Integer);
|
004785F3   E89428FCFF             call    0043AE8C
004785F8   8B55F8                 mov     edx, [ebp-$08]

* Reference to Form3
|
004785FB   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Controls.TControl.SetWidth(TControl;Integer);
|
00478600   E86328FCFF             call    0043AE68
00478605   33D2                   xor     edx, edx

* Reference to Form3
|
00478607   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
0047860C   E82F28FCFF             call    0043AE40
00478611   33D2                   xor     edx, edx

* Reference to Form3
|
00478613   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Controls.TControl.SetLeft(TControl;Integer);
|
00478618   E8FF27FCFF             call    0043AE1C
0047861D   EB54                   jmp     00478673
0047861F   8B15A8EC4700           mov     edx, [$0047ECA8]

* Reference to Form3
|
00478625   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Forms.TCustomForm.SetClientWidth(TCustomForm;Integer);
|
00478628   E8C3C3FDFF             call    004549F0
0047862D   8B15A4EC4700           mov     edx, [$0047ECA4]

* Reference to Form3
|
00478633   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Forms.TCustomForm.SetClientWidth(TCustomForm;Integer);
|
00478636   E885C3FDFF             call    004549C0

* Reference to TForm1 instance
|
0047863B   A150DC4700             mov     eax, dword ptr [$0047DC50]
00478640   8B00                   mov     eax, [eax]

* Reference to field TForm1.Top : Integer
|
00478642   8B5044                 mov     edx, [eax+$44]
00478645   83C23C                 add     edx, +$3C

* Reference to Form3
|
00478648   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
0047864D   E8EE27FCFF             call    0043AE40

* Reference to TForm1 instance
|
00478652   A150DC4700             mov     eax, dword ptr [$0047DC50]
00478657   8B00                   mov     eax, [eax]

* Reference to field TForm1.Left : Integer
|
00478659   8B5040                 mov     edx, [eax+$40]
0047865C   83C20A                 add     edx, +$0A

* Reference to Form3
|
0047865F   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Controls.TControl.SetLeft(TControl;Integer);
|
00478664   E8B327FCFF             call    0043AE1C

* Reference to Form3
|
00478669   A118EC4700             mov     eax, dword ptr [$0047EC18]

* Reference to: Forms.TCustomForm.Show(TCustomForm);
|
0047866E   E8C9F8FDFF             call    00457F3C
00478673   8BE5                   mov     esp, ebp
00478675   5D                     pop     ebp
00478676   C3                     ret

*)
end;

procedure TForm3.ChangeLight(Sender : TObject);
begin
(*

* Reference to Form3
|
00478678   A118EC4700             mov     eax, dword ptr [$0047EC18]
0047867D   0514030000             add     eax, +$00000314
00478682   50                     push    eax
00478683   6800120000             push    $00001200
00478688   6801400000             push    $00004001

* Reference to: opengl32.glLightfv()
|
0047868D   E82AADFEFF             call    004633BC
00478692   C3                     ret

*)
end;

end.