unit LibraryFunctions;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TForm2=class(TForm)
    panel2: TPanel;
    label1: TLabel;
    label2: TLabel;
    TrackBar1: TTrackBar;
    ComboBox3: TComboBox;
    procedure ComboBox3Change(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure TrackBar1Change(Sender : TObject);
    procedure FormResize(Sender : TObject);
    procedure _PROC_00478980(Sender : TObject);
    procedure _PROC_00478A20(Sender : TObject);
    procedure _PROC_00478AB4(Sender : TObject);
    procedure _PROC_00478B48(Sender : TObject);
    procedure _PROC_00478C21(Sender : TObject);
    procedure _PROC_00478CF9(Sender : TObject);
    procedure _PROC_00478F59(Sender : TObject);
    procedure _PROC_00478F88(Sender : TObject);
    procedure _PROC_00478F90(Sender : TObject);
    procedure _PROC_004790E2(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  Form2: TForm2;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TForm2.ComboBox3Change(Sender : TObject);
begin
(*
00478D70   53                     push    ebx
00478D71   8BD8                   mov     ebx, eax

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478D73   8B8308030000           mov     eax, [ebx+$0308]
00478D79   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478D7B   FF92CC000000           call    dword ptr [edx+$00CC]
00478D81   85C0                   test    eax, eax
00478D83   751C                   jnz     00478DA1

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478D85   8B8308030000           mov     eax, [ebx+$0308]
00478D8B   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478D8D   FF92CC000000           call    dword ptr [edx+$00CC]

* Reference to TForm3 instance
|
00478D93   8B1510DB4700           mov     edx, [$0047DB10]
00478D99   8B12                   mov     edx, [edx]

* Reference to field TForm3.OFFS_0310
|
00478D9B   898210030000           mov     [edx+$0310], eax

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478DA1   8B8308030000           mov     eax, [ebx+$0308]
00478DA7   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478DA9   FF92CC000000           call    dword ptr [edx+$00CC]
00478DAF   48                     dec     eax
00478DB0   751C                   jnz     00478DCE

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478DB2   8B8308030000           mov     eax, [ebx+$0308]
00478DB8   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478DBA   FF92CC000000           call    dword ptr [edx+$00CC]

* Reference to TForm3 instance
|
00478DC0   8B1510DB4700           mov     edx, [$0047DB10]
00478DC6   8B12                   mov     edx, [edx]

* Reference to field TForm3.OFFS_0310
|
00478DC8   898210030000           mov     [edx+$0310], eax

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478DCE   8B8308030000           mov     eax, [ebx+$0308]
00478DD4   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478DD6   FF92CC000000           call    dword ptr [edx+$00CC]
00478DDC   83F802                 cmp     eax, +$02
00478DDF   751C                   jnz     00478DFD

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478DE1   8B8308030000           mov     eax, [ebx+$0308]
00478DE7   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478DE9   FF92CC000000           call    dword ptr [edx+$00CC]

* Reference to TForm3 instance
|
00478DEF   8B1510DB4700           mov     edx, [$0047DB10]
00478DF5   8B12                   mov     edx, [edx]

* Reference to field TForm3.OFFS_0310
|
00478DF7   898210030000           mov     [edx+$0310], eax

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478DFD   8B8308030000           mov     eax, [ebx+$0308]
00478E03   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478E05   FF92CC000000           call    dword ptr [edx+$00CC]
00478E0B   83F803                 cmp     eax, +$03
00478E0E   751C                   jnz     00478E2C

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478E10   8B8308030000           mov     eax, [ebx+$0308]
00478E16   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478E18   FF92CC000000           call    dword ptr [edx+$00CC]

* Reference to TForm3 instance
|
00478E1E   8B1510DB4700           mov     edx, [$0047DB10]
00478E24   8B12                   mov     edx, [edx]

* Reference to field TForm3.OFFS_0310
|
00478E26   898210030000           mov     [edx+$0310], eax

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478E2C   8B8308030000           mov     eax, [ebx+$0308]
00478E32   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478E34   FF92CC000000           call    dword ptr [edx+$00CC]
00478E3A   83F804                 cmp     eax, +$04
00478E3D   751C                   jnz     00478E5B

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478E3F   8B8308030000           mov     eax, [ebx+$0308]
00478E45   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478E47   FF92CC000000           call    dword ptr [edx+$00CC]

* Reference to TForm3 instance
|
00478E4D   8B1510DB4700           mov     edx, [$0047DB10]
00478E53   8B12                   mov     edx, [edx]

* Reference to field TForm3.OFFS_0310
|
00478E55   898210030000           mov     [edx+$0310], eax

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478E5B   8B8308030000           mov     eax, [ebx+$0308]
00478E61   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478E63   FF92CC000000           call    dword ptr [edx+$00CC]
00478E69   83F805                 cmp     eax, +$05
00478E6C   751C                   jnz     00478E8A

* Reference to control TForm2.ComboBox3 : TComboBox
|
00478E6E   8B8308030000           mov     eax, [ebx+$0308]
00478E74   8B10                   mov     edx, [eax]

* Reference to method TComboBox.ItemIndex()
|
00478E76   FF92CC000000           call    dword ptr [edx+$00CC]

* Reference to TForm3 instance
|
00478E7C   8B1510DB4700           mov     edx, [$0047DB10]
00478E82   8B12                   mov     edx, [edx]

* Reference to field TForm3.OFFS_0310
|
00478E84   898210030000           mov     [edx+$0310], eax
00478E8A   5B                     pop     ebx
00478E8B   C3                     ret

*)
end;

procedure TForm2.FormCreate(Sender : TObject);
begin
(*

* Possible String Reference to: 'Àíèìàöèÿ'
|
00478E8C   BAA48E4700             mov     edx, $00478EA4

* Reference to Form2
|
00478E91   A1B8EC4700             mov     eax, dword ptr [$0047ECB8]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00478E96   E84128FCFF             call    0043B6DC
00478E9B   C3                     ret

*)
end;

procedure TForm2.TrackBar1Change(Sender : TObject);
begin
(*

* Reference to control TForm2.TrackBar1 : TTrackBar
|
00478EC4   8B9004030000           mov     edx, [eax+$0304]
00478ECA   DB8228020000           fild    dword ptr [edx+$0228]
00478ED0   D835548F4700           fdiv    dword ptr [$00478F54]

* Reference to TForm3 instance
|
00478ED6   8B1510DB4700           mov     edx, [$0047DB10]
00478EDC   8B12                   mov     edx, [edx]
00478EDE   D99A14030000           fstp    dword ptr [edx+$0314]
00478EE4   9B                     wait

* Reference to control TForm2.TrackBar1 : TTrackBar
|
00478EE5   8B9004030000           mov     edx, [eax+$0304]
00478EEB   DB8228020000           fild    dword ptr [edx+$0228]
00478EF1   D835548F4700           fdiv    dword ptr [$00478F54]

* Reference to TForm3 instance
|
00478EF7   8B1510DB4700           mov     edx, [$0047DB10]
00478EFD   8B12                   mov     edx, [edx]
00478EFF   D99A18030000           fstp    dword ptr [edx+$0318]
00478F05   9B                     wait

* Reference to control TForm2.TrackBar1 : TTrackBar
|
00478F06   8B9004030000           mov     edx, [eax+$0304]
00478F0C   DB8228020000           fild    dword ptr [edx+$0228]
00478F12   D835548F4700           fdiv    dword ptr [$00478F54]

* Reference to TForm3 instance
|
00478F18   8B1510DB4700           mov     edx, [$0047DB10]
00478F1E   8B12                   mov     edx, [edx]
00478F20   D99A1C030000           fstp    dword ptr [edx+$031C]
00478F26   9B                     wait

* Reference to control TForm2.TrackBar1 : TTrackBar
|
00478F27   8B8004030000           mov     eax, [eax+$0304]
00478F2D   DB8028020000           fild    dword ptr [eax+$0228]
00478F33   D835548F4700           fdiv    dword ptr [$00478F54]

* Reference to TForm3 instance
|
00478F39   A110DB4700             mov     eax, dword ptr [$0047DB10]
00478F3E   8B00                   mov     eax, [eax]
00478F40   D99820030000           fstp    dword ptr [eax+$0320]
00478F46   9B                     wait

* Reference to TForm3 instance
|
00478F47   A110DB4700             mov     eax, dword ptr [$0047DB10]
00478F4C   8B00                   mov     eax, [eax]

* Reference to : TForm3.ChangeLight()
|
00478F4E   E825F7FFFF             call    00478678
00478F53   C3                     ret

*)
end;

procedure TForm2.FormResize(Sender : TObject);
begin
(*
00478EB0   BA46000000             mov     edx, $00000046

* Reference to control TForm2.TrackBar1 : TTrackBar
|
00478EB5   8B8004030000           mov     eax, [eax+$0304]

* Reference to: ComCtrls.TTrackBar.SetPosition(TTrackBar;Integer);
|
00478EBB   E87073FEFF             call    00460230
00478EC0   C3                     ret

*)
end;

procedure TForm2._PROC_00478980(Sender : TObject);
begin
(*
00478980   55                     push    ebp
00478981   8BEC                   mov     ebp, esp
00478983   83C4F4                 add     esp, -$0C
00478986   53                     push    ebx
00478987   56                     push    esi
00478988   57                     push    edi
00478989   33C9                   xor     ecx, ecx
0047898B   894DF4                 mov     [ebp-$0C], ecx
0047898E   8955F8                 mov     [ebp-$08], edx
00478991   8945FC                 mov     [ebp-$04], eax

* Reference to Form2
|
00478994   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00478997   E86CC2F8FF             call    00404C08
0047899C   33C0                   xor     eax, eax
0047899E   55                     push    ebp
0047899F   68128A4700             push    $00478A12

***** TRY
|
004789A4   64FF30                 push    dword ptr fs:[eax]
004789A7   648920                 mov     fs:[eax], esp

* Reference to Form2
|
004789AA   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
004789AD   E866C0F8FF             call    00404A18
004789B2   8BD8                   mov     ebx, eax
004789B4   8D45F4                 lea     eax, [ebp-$0C]
004789B7   8BD3                   mov     edx, ebx

* Reference to: System.@LStrSetLength;
|
004789B9   E8E6C3F8FF             call    00404DA4

* Reference to Form2
|
004789BE   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
004789C1   E852C0F8FF             call    00404A18
004789C6   8BF0                   mov     esi, eax
004789C8   85F6                   test    esi, esi
004789CA   7E1D                   jle     004789E9
004789CC   BF01000000             mov     edi, $00000001
004789D1   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: crtl.__pure_error_;
|
004789D4   E897C2F8FF             call    00404C70

* Reference to Form2
|
004789D9   8B55FC                 mov     edx, [ebp-$04]
004789DC   8A543AFF               mov     dl, byte ptr [edx+edi-$01]
004789E0   885418FF               mov     [eax+ebx-$01], dl
004789E4   4B                     dec     ebx
004789E5   47                     inc     edi
004789E6   4E                     dec     esi
004789E7   75E8                   jnz     004789D1
004789E9   8B45F8                 mov     eax, [ebp-$08]
004789EC   8B55F4                 mov     edx, [ebp-$0C]

* Reference to: System.@LStrAsg(void;void;void;void);
|
004789EF   E8B8BDF8FF             call    004047AC
004789F4   33C0                   xor     eax, eax
004789F6   5A                     pop     edx
004789F7   59                     pop     ecx
004789F8   59                     pop     ecx
004789F9   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]ÃU‹ìƒÄøSVW3É‰Mø‹ú‰Eü‹EüèÍÁøÿ3
|                                ÀUh¦ŠG'
|
004789FC   68198A4700             push    $00478A19
00478A01   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
00478A04   E84FBDF8FF             call    00404758
00478A09   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00478A0C   E847BDF8FF             call    00404758
00478A11   C3                     ret


* Reference to: System.@HandleFinally;
|
00478A12   E91DB7F8FF             jmp     00404134
00478A17   EBE8                   jmp     00478A01

****** END
|
00478A19   5F                     pop     edi
00478A1A   5E                     pop     esi
00478A1B   5B                     pop     ebx
00478A1C   8BE5                   mov     esp, ebp
00478A1E   5D                     pop     ebp
00478A1F   C3                     ret

*)
end;

procedure TForm2._PROC_00478A20(Sender : TObject);
begin
(*
00478A20   55                     push    ebp
00478A21   8BEC                   mov     ebp, esp
00478A23   83C4F8                 add     esp, -$08
00478A26   53                     push    ebx
00478A27   56                     push    esi
00478A28   57                     push    edi
00478A29   33C9                   xor     ecx, ecx
00478A2B   894DF8                 mov     [ebp-$08], ecx
00478A2E   8BFA                   mov     edi, edx
00478A30   8945FC                 mov     [ebp-$04], eax

* Reference to Form2
|
00478A33   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00478A36   E8CDC1F8FF             call    00404C08
00478A3B   33C0                   xor     eax, eax
00478A3D   55                     push    ebp

* Possible String Reference to: 'é‰¶øÿëë_^[YY]ÃU‹ìƒÄøSVW3É‰Mø‹ú‰Eü‹E
|                                üè9Áøÿ3ÀUh:‹G'
|
00478A3E   68A68A4700             push    $00478AA6

***** TRY
|
00478A43   64FF30                 push    dword ptr fs:[eax]
00478A46   648920                 mov     fs:[eax], esp

* Reference to Form2
|
00478A49   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
00478A4C   E8C7BFF8FF             call    00404A18
00478A51   8BD8                   mov     ebx, eax
00478A53   33F6                   xor     esi, esi
00478A55   EB1F                   jmp     00478A76
00478A57   46                     inc     esi
00478A58   8D45F8                 lea     eax, [ebp-$08]
00478A5B   8BD6                   mov     edx, esi

* Reference to: System.@LStrSetLength;
|
00478A5D   E842C3F8FF             call    00404DA4
00478A62   8D45F8                 lea     eax, [ebp-$08]

* Reference to: crtl.__pure_error_;
|
00478A65   E806C2F8FF             call    00404C70

* Reference to Form2
|
00478A6A   8B55FC                 mov     edx, [ebp-$04]
00478A6D   8A541AFF               mov     dl, byte ptr [edx+ebx-$01]
00478A71   885430FF               mov     [eax+esi-$01], dl
00478A75   4B                     dec     ebx

* Reference to Form2
|
00478A76   8B45FC                 mov     eax, [ebp-$04]
00478A79   8A4418FF               mov     al, byte ptr [eax+ebx-$01]
00478A7D   3C2E                   cmp     al, $2E
00478A7F   75D6                   jnz     00478A57
00478A81   8BD7                   mov     edx, edi
00478A83   8B45F8                 mov     eax, [ebp-$08]

* Reference to : TForm2._PROC_00478980()
|
00478A86   E8F5FEFFFF             call    00478980
00478A8B   33C0                   xor     eax, eax
00478A8D   5A                     pop     edx
00478A8E   59                     pop     ecx
00478A8F   59                     pop     ecx
00478A90   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[YY]ÃU‹ìƒÄøSVW3É‰Mø‹ú‰Eü‹Eüè9Áøÿ3
|                                ÀUh:‹G'
|
00478A93   68AD8A4700             push    $00478AAD
00478A98   8D45F8                 lea     eax, [ebp-$08]
00478A9B   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00478AA0   E8D7BCF8FF             call    0040477C
00478AA5   C3                     ret


* Reference to: System.@HandleFinally;
|
00478AA6   E989B6F8FF             jmp     00404134
00478AAB   EBEB                   jmp     00478A98

****** END
|
00478AAD   5F                     pop     edi
00478AAE   5E                     pop     esi
00478AAF   5B                     pop     ebx
00478AB0   59                     pop     ecx
00478AB1   59                     pop     ecx
00478AB2   5D                     pop     ebp
00478AB3   C3                     ret

*)
end;

procedure TForm2._PROC_00478AB4(Sender : TObject);
begin
(*
00478AB4   55                     push    ebp
00478AB5   8BEC                   mov     ebp, esp
00478AB7   83C4F8                 add     esp, -$08
00478ABA   53                     push    ebx
00478ABB   56                     push    esi
00478ABC   57                     push    edi
00478ABD   33C9                   xor     ecx, ecx
00478ABF   894DF8                 mov     [ebp-$08], ecx
00478AC2   8BFA                   mov     edi, edx
00478AC4   8945FC                 mov     [ebp-$04], eax

* Reference to Form2
|
00478AC7   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00478ACA   E839C1F8FF             call    00404C08
00478ACF   33C0                   xor     eax, eax
00478AD1   55                     push    ebp
00478AD2   683A8B4700             push    $00478B3A

***** TRY
|
00478AD7   64FF30                 push    dword ptr fs:[eax]
00478ADA   648920                 mov     fs:[eax], esp

* Reference to Form2
|
00478ADD   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
00478AE0   E833BFF8FF             call    00404A18
00478AE5   8BD8                   mov     ebx, eax
00478AE7   33F6                   xor     esi, esi
00478AE9   EB1F                   jmp     00478B0A
00478AEB   46                     inc     esi
00478AEC   8D45F8                 lea     eax, [ebp-$08]
00478AEF   8BD6                   mov     edx, esi

* Reference to: System.@LStrSetLength;
|
00478AF1   E8AEC2F8FF             call    00404DA4
00478AF6   8D45F8                 lea     eax, [ebp-$08]

* Reference to: crtl.__pure_error_;
|
00478AF9   E872C1F8FF             call    00404C70

* Reference to Form2
|
00478AFE   8B55FC                 mov     edx, [ebp-$04]
00478B01   8A541AFF               mov     dl, byte ptr [edx+ebx-$01]
00478B05   885430FF               mov     [eax+esi-$01], dl
00478B09   4B                     dec     ebx

* Reference to Form2
|
00478B0A   8B45FC                 mov     eax, [ebp-$04]
00478B0D   8A4418FF               mov     al, byte ptr [eax+ebx-$01]
00478B11   3C5C                   cmp     al, $5C
00478B13   75D6                   jnz     00478AEB
00478B15   8BD7                   mov     edx, edi
00478B17   8B45F8                 mov     eax, [ebp-$08]

* Reference to : TForm2._PROC_00478980()
|
00478B1A   E861FEFFFF             call    00478980
00478B1F   33C0                   xor     eax, eax
00478B21   5A                     pop     edx
00478B22   59                     pop     ecx
00478B23   59                     pop     ecx
00478B24   648910                 mov     fs:[eax], edx

****** FINALLY
|
00478B27   68418B4700             push    $00478B41
00478B2C   8D45F8                 lea     eax, [ebp-$08]
00478B2F   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00478B34   E843BCF8FF             call    0040477C
00478B39   C3                     ret


* Reference to: System.@HandleFinally;
|
00478B3A   E9F5B5F8FF             jmp     00404134
00478B3F   EBEB                   jmp     00478B2C

****** END
|
00478B41   5F                     pop     edi
00478B42   5E                     pop     esi
00478B43   5B                     pop     ebx
00478B44   59                     pop     ecx
00478B45   59                     pop     ecx
00478B46   5D                     pop     ebp
00478B47   C3                     ret

*)
end;

procedure TForm2._PROC_00478B48(Sender : TObject);
begin
(*
00478B48   55                     push    ebp
00478B49   8BEC                   mov     ebp, esp
00478B4B   33C9                   xor     ecx, ecx
00478B4D   51                     push    ecx
00478B4E   51                     push    ecx
00478B4F   51                     push    ecx
00478B50   51                     push    ecx
00478B51   51                     push    ecx
00478B52   53                     push    ebx
00478B53   56                     push    esi
00478B54   57                     push    edi
00478B55   8955F8                 mov     [ebp-$08], edx
00478B58   8945FC                 mov     [ebp-$04], eax

* Reference to Form2
|
00478B5B   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00478B5E   E8A5C0F8FF             call    00404C08
00478B63   33C0                   xor     eax, eax
00478B65   55                     push    ebp
00478B66   68068C4700             push    $00478C06

***** TRY
|
00478B6B   64FF30                 push    dword ptr fs:[eax]
00478B6E   648920                 mov     fs:[eax], esp

* Reference to Form2
|
00478B71   8B45FC                 mov     eax, [ebp-$04]

* Reference to: SysUtils.StrToInt(AnsiString):Integer;
|
00478B74   E877FEF8FF             call    004089F0
00478B79   B9E8030000             mov     ecx, $000003E8
00478B7E   99                     cdq
00478B7F   F7F9                   idiv    ecx 
00478B81   8BF0                   mov     esi, eax
00478B83   8BC6                   mov     eax, esi
00478B85   B93C000000             mov     ecx, $0000003C
00478B8A   99                     cdq
00478B8B   F7F9                   idiv    ecx 
00478B8D   8BD8                   mov     ebx, eax
00478B8F   8BC3                   mov     eax, ebx
00478B91   B93C000000             mov     ecx, $0000003C
00478B96   99                     cdq
00478B97   F7F9                   idiv    ecx 
00478B99   8BF8                   mov     edi, eax
00478B9B   6BC73C                 imul    eax, edi, $3C
00478B9E   2BD8                   sub     ebx, eax
00478BA0   6BC33C                 imul    eax, ebx, $3C
00478BA3   2BF0                   sub     esi, eax
00478BA5   8D55F4                 lea     edx, [ebp-$0C]
00478BA8   8BC7                   mov     eax, edi

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00478BAA   E805FDF8FF             call    004088B4
00478BAF   FF75F4                 push    dword ptr [ebp-$0C]
00478BB2   681C8C4700             push    $00478C1C
00478BB7   8D55F0                 lea     edx, [ebp-$10]
00478BBA   8BC3                   mov     eax, ebx

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00478BBC   E8F3FCF8FF             call    004088B4
00478BC1   FF75F0                 push    dword ptr [ebp-$10]
00478BC4   681C8C4700             push    $00478C1C
00478BC9   8D55EC                 lea     edx, [ebp-$14]
00478BCC   8BC6                   mov     eax, esi

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00478BCE   E8E1FCF8FF             call    004088B4
00478BD3   FF75EC                 push    dword ptr [ebp-$14]
00478BD6   8B45F8                 mov     eax, [ebp-$08]
00478BD9   BA05000000             mov     edx, $00000005

* Reference to: System.@LStrCatN;
|
00478BDE   E8F5BEF8FF             call    00404AD8
00478BE3   33C0                   xor     eax, eax
00478BE5   5A                     pop     edx
00478BE6   59                     pop     ecx
00478BE7   59                     pop     ecx
00478BE8   648910                 mov     fs:[eax], edx

****** FINALLY
|
00478BEB   680D8C4700             push    $00478C0D
00478BF0   8D45EC                 lea     eax, [ebp-$14]
00478BF3   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00478BF8   E87FBBF8FF             call    0040477C
00478BFD   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00478C00   E853BBF8FF             call    00404758
00478C05   C3                     ret


* Reference to: System.@HandleFinally;
|
00478C06   E929B5F8FF             jmp     00404134
00478C0B   EBE3                   jmp     00478BF0

****** END
|
00478C0D   5F                     pop     edi
00478C0E   5E                     pop     esi
00478C0F   5B                     pop     ebx
00478C10   8BE5                   mov     esp, ebp
00478C12   5D                     pop     ebp
00478C13   C3                     ret

*)
end;

procedure TForm2._PROC_00478C21(Sender : TObject);
begin
(*
00478C21   8BEC                   mov     ebp, esp
00478C23   33C9                   xor     ecx, ecx
00478C25   51                     push    ecx
00478C26   51                     push    ecx
00478C27   51                     push    ecx
00478C28   51                     push    ecx
00478C29   51                     push    ecx
00478C2A   53                     push    ebx
00478C2B   56                     push    esi
00478C2C   57                     push    edi
00478C2D   8955F8                 mov     [ebp-$08], edx
00478C30   8945FC                 mov     [ebp-$04], eax

* Reference to Form2
|
00478C33   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00478C36   E8CDBFF8FF             call    00404C08
00478C3B   33C0                   xor     eax, eax
00478C3D   55                     push    ebp
00478C3E   68DE8C4700             push    $00478CDE

***** TRY
|
00478C43   64FF30                 push    dword ptr fs:[eax]
00478C46   648920                 mov     fs:[eax], esp

* Reference to Form2
|
00478C49   8B45FC                 mov     eax, [ebp-$04]

* Reference to: SysUtils.StrToInt(AnsiString):Integer;
|
00478C4C   E89FFDF8FF             call    004089F0
00478C51   B918000000             mov     ecx, $00000018
00478C56   99                     cdq
00478C57   F7F9                   idiv    ecx 
00478C59   8BF0                   mov     esi, eax
00478C5B   8BC6                   mov     eax, esi
00478C5D   B93C000000             mov     ecx, $0000003C
00478C62   99                     cdq
00478C63   F7F9                   idiv    ecx 
00478C65   8BD8                   mov     ebx, eax
00478C67   8BC3                   mov     eax, ebx
00478C69   B93C000000             mov     ecx, $0000003C
00478C6E   99                     cdq
00478C6F   F7F9                   idiv    ecx 
00478C71   8BF8                   mov     edi, eax
00478C73   6BC73C                 imul    eax, edi, $3C
00478C76   2BD8                   sub     ebx, eax
00478C78   6BC33C                 imul    eax, ebx, $3C
00478C7B   2BF0                   sub     esi, eax
00478C7D   8D55F4                 lea     edx, [ebp-$0C]
00478C80   8BC7                   mov     eax, edi

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00478C82   E82DFCF8FF             call    004088B4
00478C87   FF75F4                 push    dword ptr [ebp-$0C]
00478C8A   68F48C4700             push    $00478CF4
00478C8F   8D55F0                 lea     edx, [ebp-$10]
00478C92   8BC3                   mov     eax, ebx

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00478C94   E81BFCF8FF             call    004088B4
00478C99   FF75F0                 push    dword ptr [ebp-$10]
00478C9C   68F48C4700             push    $00478CF4
00478CA1   8D55EC                 lea     edx, [ebp-$14]
00478CA4   8BC6                   mov     eax, esi

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
00478CA6   E809FCF8FF             call    004088B4
00478CAB   FF75EC                 push    dword ptr [ebp-$14]
00478CAE   8B45F8                 mov     eax, [ebp-$08]
00478CB1   BA05000000             mov     edx, $00000005

* Reference to: System.@LStrCatN;
|
00478CB6   E81DBEF8FF             call    00404AD8
00478CBB   33C0                   xor     eax, eax
00478CBD   5A                     pop     edx
00478CBE   59                     pop     ecx
00478CBF   59                     pop     ecx
00478CC0   648910                 mov     fs:[eax], edx

****** FINALLY
|
00478CC3   68E58C4700             push    $00478CE5
00478CC8   8D45EC                 lea     eax, [ebp-$14]
00478CCB   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00478CD0   E8A7BAF8FF             call    0040477C
00478CD5   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00478CD8   E87BBAF8FF             call    00404758
00478CDD   C3                     ret


* Reference to: System.@HandleFinally;
|
00478CDE   E951B4F8FF             jmp     00404134
00478CE3   EBE3                   jmp     00478CC8

****** END
|
00478CE5   5F                     pop     edi
00478CE6   5E                     pop     esi
00478CE7   5B                     pop     ebx
00478CE8   8BE5                   mov     esp, ebp
00478CEA   5D                     pop     ebp
00478CEB   C3                     ret

*)
end;

procedure TForm2._PROC_00478CF9(Sender : TObject);
begin
(*
00478CF9   8BEC                   mov     ebp, esp
00478CFB   83C4F8                 add     esp, -$08
00478CFE   53                     push    ebx
00478CFF   33C9                   xor     ecx, ecx
00478D01   894DF8                 mov     [ebp-$08], ecx
00478D04   8BDA                   mov     ebx, edx
00478D06   8945FC                 mov     [ebp-$04], eax

* Reference to Form2
|
00478D09   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00478D0C   E8F7BEF8FF             call    00404C08
00478D11   33C0                   xor     eax, eax
00478D13   55                     push    ebp
00478D14   68628D4700             push    $00478D62

***** TRY
|
00478D19   64FF30                 push    dword ptr fs:[eax]
00478D1C   648920                 mov     fs:[eax], esp
00478D1F   8D55F8                 lea     edx, [ebp-$08]

* Reference to Form2
|
00478D22   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TForm2._PROC_00478980()
|
00478D25   E856FCFFFF             call    00478980
00478D2A   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.@LStrLen(String):Integer;
|
00478D2D   E8E6BCF8FF             call    00404A18
00478D32   8BD0                   mov     edx, eax
00478D34   4A                     dec     edx
00478D35   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrSetLength;
|
00478D38   E867C0F8FF             call    00404DA4
00478D3D   8BD3                   mov     edx, ebx
00478D3F   8B45F8                 mov     eax, [ebp-$08]

* Reference to : TForm2._PROC_00478980()
|
00478D42   E839FCFFFF             call    00478980
00478D47   33C0                   xor     eax, eax
00478D49   5A                     pop     edx
00478D4A   59                     pop     ecx
00478D4B   59                     pop     ecx
00478D4C   648910                 mov     fs:[eax], edx

****** FINALLY
|
00478D4F   68698D4700             push    $00478D69
00478D54   8D45F8                 lea     eax, [ebp-$08]
00478D57   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00478D5C   E81BBAF8FF             call    0040477C
00478D61   C3                     ret


* Reference to: System.@HandleFinally;
|
00478D62   E9CDB3F8FF             jmp     00404134
00478D67   EBEB                   jmp     00478D54

****** END
|
00478D69   5B                     pop     ebx
00478D6A   59                     pop     ecx
00478D6B   59                     pop     ecx
00478D6C   5D                     pop     ebp
00478D6D   C3                     ret

*)
end;

procedure TForm2._PROC_00478F59(Sender : TObject);
begin
(*
00478F59   8BEC                   mov     ebp, esp
00478F5B   33C0                   xor     eax, eax
00478F5D   55                     push    ebp

* Possible String Reference to: 'é²±øÿëø]Ã‹Àƒ-¼ìG'
|
00478F5E   687D8F4700             push    $00478F7D

***** TRY
|
00478F63   64FF30                 push    dword ptr fs:[eax]
00478F66   648920                 mov     fs:[eax], esp
00478F69   FF05BCEC4700           inc     dword ptr [$0047ECBC]
00478F6F   33C0                   xor     eax, eax
00478F71   5A                     pop     edx
00478F72   59                     pop     ecx
00478F73   59                     pop     ecx
00478F74   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-¼ìG'
|
00478F77   68848F4700             push    $00478F84
00478F7C   C3                     ret


* Reference to: System.@HandleFinally;
|
00478F7D   E9B2B1F8FF             jmp     00404134
00478F82   EBF8                   jmp     00478F7C

****** END
|
00478F84   5D                     pop     ebp
00478F85   C3                     ret

*)
end;

procedure TForm2._PROC_00478F88(Sender : TObject);
begin
(*
00478F88   832DBCEC470001         sub     dword ptr [$0047ECBC], +$01
00478F8F   C3                     ret

*)
end;

procedure TForm2._PROC_00478F90(Sender : TObject);
begin
(*
00478F90   94                     xchg    eax, esp
00478F91   8F4700                 pop     dword ptr [edi+$00]
00478F94   1102                   adc     [edx], eax
00478F96   2E320400               xor     al, byte ptr cs:[eax+eax]
00478F9A   0000                   add     [eax], al

*)
end;

procedure TForm2._PROC_004790E2(Sender : TObject);
begin
(*
004790E2   45                     inc     ebp
004790E3   00783D                 add     [eax+$3D], bh
004790E6   45                     inc     ebp
004790E7   0038                   add     [eax], bh
004790E9   7E45                   jle     00479130
004790EB   0010                   add     [eax], dl
004790ED   6545                   inc     ebp
004790EF   00EC                   add     ah, ch
004790F1   7F45                   jnle    00479138
004790F3   00C8                   add     al, cl
004790F5   4A                     dec     edx
004790F6   45                     inc     ebp
004790F7   000E                   add     [esi], cl
004790F9   0000                   add     [eax], al

004790FB   0000                   add     [eax], al

004790FD   0001                   add     [ecx], al
004790FF   0000                   add     [eax], al

00479101   00908F470090           add     [eax+$9000478F], dl
00479107   0300                   add     eax, [eax]
00479109   0026                   add     [esi], ah
0047910B   0099954700F8           add     [ecx+$F8004795], bl
00479111   0200                   add     al, byte ptr [eax]
00479113   0000                   add     [eax], al

00479115   0006                   add     [esi], al
00479117   7061                   jo      0047917A
00479119   6E                     outsb
0047911A   656C                   insb
0047911C   31FC                   xor     esp, edi
0047911E   0200                   add     al, byte ptr [eax]
00479120   0001                   add     [ecx], al
00479122   000474                 add     [esp+esi*2], al
00479125   6D                     insd
00479126   7231                   jb      00479159
00479128   0003                   add     [ebx], al
0047912A   0000                   add     [eax], al

0047912C   0200                   add     al, byte ptr [eax]
0047912E   0C6D                   or      al, $6D
00479130   65646961706C617965     imul    esp, fs:[ecx+$70], $6579616C
00479139   7231                   jb      0047916C
0047913B   0403                   add     al, +$03
0047913D   0000                   add     [eax], al

0047913F   0300                   add     eax, [eax]
00479141   0C4C                   or      al, $4C
00479143   697374426F7874         imul    esi, [ebx+$74], $74786F42
0047914A   7261                   jb      004791AD
0047914C   636B08                 arpl    [ebx+$08], bp
0047914F   0300                   add     eax, [eax]
00479151   000400                 add     [eax+eax], al
00479154   08646C67               or      [esp+ebp*2+$67], ah
00479158   4F                     dec     edi
00479159   7065                   jo      004791C0
0047915B   6E                     outsb
0047915C   310C03                 xor     [ebx+eax], ecx
0047915F   0000                   add     [eax], al

00479161   05000D536F             add     eax, +$6F530D00
00479166   756E                   jnz     004791D6
00479168   6454                   push    esp
0047916A   7261                   jb      004791CD
0047916C   636B42                 arpl    [ebx+$42], bp
0047916F   61                     popa
00479170   7210                   jb      00479182
00479172   0300                   add     eax, [eax]
00479174   0005000E566F           add     [$6F560E00], al
0047917A   6C                     insb
0047917B   756D                   jnz     004791EA
0047917D   6554                   push    esp
0047917F   7261                   jb      004791E2
00479181   636B42                 arpl    [ebx+$42], bp
00479184   61                     popa
00479185   7214                   jb      0047919B
00479187   0300                   add     eax, [eax]
00479189   0006                   add     [esi], al
0047918B   000B                   add     [ebx], cl
0047918D   637572                 arpl    [ebp+$72], si
00479190   7265                   jb      004791F7
00479192   6E                     outsb
00479193   7473                   jz      00479208
00479195   6F                     outsd
00479196   6E                     outsb
00479197   671803                 sbb     [bp+di], al
0047919A   0000                   add     [eax], al

0047919C   06                     push    es
0047919D   0008                   add     [eax], cl
0047919F   7072                   jo      00479213
004791A1   657673                 jbe     00479217
004791A4   6F                     outsd
004791A5   6E                     outsb
004791A6   671C03                 sbb     al, $03
004791A9   0000                   add     [eax], al

004791AB   06                     push    es
004791AC   0008                   add     [eax], cl
004791AE   6E                     outsb
004791AF   657874                 js      00479226
004791B2   736F                   jnb     00479223
004791B4   6E                     outsb
004791B5   672003                 and     [bp+di], al
004791B8   0000                   add     [eax], al

004791BA   06                     push    es
004791BB   0008                   add     [eax], cl
004791BD   54                     push    esp
004791BE   696D65536F6E67         imul    ebp, [ebp+$65], $676E6F53
004791C5   2403                   and     al, $03
004791C7   0000                   add     [eax], al

004791C9   06                     push    es
004791CA   000B                   add     [ebx], cl
004791CC   43                     inc     ebx
004791CD   7572                   jnz     00479241
004791CF   54                     push    esp
004791D0   696D65536F6E67         imul    ebp, [ebp+$65], $676E6F53
004791D7   2803                   sub     [ebx], al
004791D9   0000                   add     [eax], al

004791DB   06                     push    es
004791DC   0009                   add     [ecx], cl
004791DE   6C                     insb
004791DF   61                     popa
004791E0   62656C                 bound   esp, qword ptr [ebp+$6C]
004791E3   44                     inc     esp
004791E4   61                     popa
004791E5   7465                   jz      0047924C
004791E7   2C03                   sub     al, $03
004791E9   0000                   add     [eax], al

004791EB   06                     push    es
004791EC   0009                   add     [ecx], cl
004791EE   6C                     insb
004791EF   61                     popa
004791F0   62656C                 bound   esp, qword ptr [ebp+$6C]
004791F3   54                     push    esp
004791F4   696D6530030000         imul    ebp, [ebp+$65], $00000330
004791FB   07                     pop     es
004791FC   0009                   add     [ecx], cl
004791FE   4D                     dec     ebp
004791FF   61                     popa
00479200   696E4D656E7531         imul    ebp, [esi+$4D], $31756E65
00479207   3403                   xor     al, $03
00479209   0000                   add     [eax], al

0047920B   0800                   or      [eax], al
0047920D   084D65                 or      [ebp+$65], cl
00479210   6E                     outsb
00479211   7546                   jnz     00479259
00479213   696C653803000008       imul    ebp, [ebp+$38], $08000003
0047921B   000A                   add     [edx], cl
0047921D   4F                     dec     edi
0047921E   7065                   jo      00479285
00479220   6E                     outsb
00479221   46                     inc     esi
00479222   6F                     outsd
00479223   6C                     insb
00479224   6465723C               jb      00479264
00479228   0300                   add     eax, [eax]
0047922A   0008                   add     [eax], cl
0047922C   000C53                 add     [ebx+edx*2], cl
0047922F   61                     popa
00479230   7665                   jbe     00479297
00479232   50                     push    eax
00479233   6C                     insb
00479234   61                     popa
00479235   796C                   jns     004792A3
00479237   69737440030000         imul    esi, [ebx+$74], $00000340
0047923E   0800                   or      [eax], al
00479240   0C4F                   or      al, $4F
00479242   7065                   jo      004792A9
00479244   6E                     outsb
00479245   50                     push    eax
00479246   6C                     insb
00479247   61                     popa
00479248   796C                   jns     004792B6
0047924A   69737444030000         imul    esi, [ebx+$74], $00000344
00479251   0900                   or      [eax], eax
00479253   0F50                   DB  $0F, $50  //
00479255   6C                     insb
00479256   61                     popa
00479257   7953                   jns     004792AC
00479259   7065                   jo      004792C0
0047925B   656442                 inc     edx
0047925E   7574                   jnz     004792D4
00479260   746F                   jz      004792D1
00479262   6E                     outsb
00479263   48                     dec     eax
00479264   0300                   add     eax, [eax]
00479266   0009                   add     [ecx], cl
00479268   0010                   add     [eax], dl
0047926A   50                     push    eax
0047926B   61                     popa
0047926C   7573                   jnz     004792E1
0047926E   6553                   push    ebx
00479270   7065                   jo      004792D7
00479272   656442                 inc     edx
00479275   7574                   jnz     004792EB
00479277   746F                   jz      004792E8
00479279   6E                     outsb
0047927A   4C                     dec     esp
0047927B   0300                   add     eax, [eax]
0047927D   0009                   add     [ecx], cl
0047927F   000F                   add     [edi], cl
00479281   4E                     dec     esi
00479282   657874                 js      004792F9
00479285   53                     push    ebx
00479286   7065                   jo      004792ED
00479288   656442                 inc     edx
0047928B   7574                   jnz     00479301
0047928D   746F                   jz      004792FE
0047928F   6E                     outsb
00479290   50                     push    eax
00479291   0300                   add     eax, [eax]
00479293   0009                   add     [ecx], cl
00479295   001450                 add     [eax+edx*2], dl
00479298   7265                   jb      004792FF
0047929A   7669                   jbe     00479305
0047929C   756F                   jnz     0047930D
0047929E   7365                   jnb     00479305
004792A0   53                     push    ebx
004792A1   7065                   jo      00479308
004792A3   656442                 inc     edx
004792A6   7574                   jnz     0047931C
004792A8   746F                   jz      00479319
004792AA   6E                     outsb
004792AB   54                     push    esp
004792AC   0300                   add     eax, [eax]
004792AE   0008                   add     [eax], cl
004792B0   000C4F                 add     [edi+ecx*2], cl
004792B3   7065                   jo      0047931A
004792B5   6E                     outsb
004792B6   46                     inc     esi
004792B7   696C654D656E7558       imul    ebp, [ebp+$4D], $58756E65
004792BF   0300                   add     eax, [eax]
004792C1   0006                   add     [esi], al
004792C3   000E                   add     [esi], cl
004792C5   7275                   jb      0047933C
004792C7   6E                     outsb
004792C8   7374                   jnb     0047933E
004792CA   7269                   jb      00479335
004792CC   6E                     outsb
004792CD   676C                   insb
004792CF   61                     popa
004792D0   62656C                 bound   esp, qword ptr [ebp+$6C]
004792D3   5C                     pop     esp
004792D4   0300                   add     eax, [eax]
004792D6   0008                   add     [eax], cl
004792D8   00044578697460         add     [$60746978+eax*2], al
004792DF   0300                   add     eax, [eax]
004792E1   0006                   add     [esi], al
004792E3   000B                   add     [ebx], cl
004792E5   766F                   jbe     00479356
004792E7   6C                     insb
004792E8   756D                   jnz     00479357
004792EA   656C                   insb
004792EC   61                     popa
004792ED   62656C                 bound   esp, qword ptr [ebp+$6C]
004792F0   640300                 add     eax, fs:[eax]
004792F3   0008                   add     [eax], cl
004792F5   0009                   add     [ecx], cl
004792F7   41                     inc     ecx
004792F8   6E                     outsb
004792F9   696D6174696F6E         imul    ebp, [ebp+$61], $6E6F6974
00479300   680300000A             push    $0A000003
00479305   0008                   add     [eax], cl
00479307   646C                   insb
00479309   6753                   push    ebx
0047930B   61                     popa
0047930C   7665                   jbe     00479373
0047930E   316C0300               xor     [ebx+eax+$00], ebp
00479312   0008                   add     [eax], cl
00479314   0002                   add     [edx], al
00479316   4E                     dec     esi
00479317   317003                 xor     [eax+$03], esi
0047931A   0000                   add     [eax], al

0047931C   0800                   or      [eax], al
0047931E   024E32                 add     cl, byte ptr [esi+$32]
00479321   7403                   jz      00479326
00479323   0000                   add     [eax], al

00479325   0800                   or      [eax], al
00479327   024E33                 add     cl, byte ptr [esi+$33]
0047932A   7803                   js      0047932F
0047932C   0000                   add     [eax], al

0047932E   0B00                   or      eax, [eax]
00479330   0A506F                 or      dl, byte ptr [eax+$6F]
00479333   7075                   jo      004793AA
00479335   704D                   jo      00479384
00479337   656E                   outsb
00479339   7531                   jnz     0047936C
0047933B   7C03                   jl      00479340
0047933D   0000                   add     [eax], al

0047933F   0800                   or      [eax], al
00479341   024E34                 add     cl, byte ptr [esi+$34]
00479344   800300                 add     byte ptr [ebx], $00
00479347   0008                   add     [eax], cl
00479349   0002                   add     [edx], al
0047934B   4E                     dec     esi
0047934C   3584030000             xor     eax, $00000384
00479351   0800                   or      [eax], al
00479353   024E36                 add     cl, byte ptr [esi+$36]
00479356   8803                   mov     [ebx], al
00479358   0000                   add     [eax], al

0047935A   06                     push    es
0047935B   0006                   add     [esi], al
0047935D   6C                     insb
0047935E   61                     popa
0047935F   62656C                 bound   esp, qword ptr [ebp+$6C]
00479362   328C0300000C00         xor     cl, byte ptr [ebx+eax+$C0000]
00479369   0B5850                 or      ebx, [eax+$50]
0047936C   4D                     dec     ebp
0047936D   61                     popa
0047936E   6E                     outsb
0047936F   69666573743119         imul    esp, [esi+$65], $19317473
00479376   0018                   add     [eax], bl
00479378   005C9C47               add     [esp+ebx*4+$47], bl
0047937C   0011                   add     [ecx], dl
0047937E   4C                     dec     esp
0047937F   697374426F7874         imul    esi, [ebx+$74], $74786F42
00479386   7261                   jb      004793E9
00479388   636B43                 arpl    [ebx+$43], bp
0047938B   6C                     insb
0047938C   69636B1100BC9D         imul    esp, [ebx+$6B], $9DBC0011
00479393   47                     inc     edi
00479394   000A                   add     [edx], cl
00479396   46                     inc     esi
00479397   6F                     outsd
00479398   726D                   jb      00479407
0047939A   43                     inc     ebx
0047939B   7265                   jb      00479402
0047939D   61                     popa
0047939E   7465                   jz      00479405
004793A0   1000                   adc     [eax], al
004793A2   749E                   jz      00479342
004793A4   47                     inc     edi
004793A5   0009                   add     [ecx], cl
004793A7   746D                   jz      00479416
004793A9   7231                   jb      004793DC
004793AB   54                     push    esp
004793AC   696D65721800A0         imul    ebp, [ebp+$65], $A0001872
004793B3   A04700116D             mov     al, byte ptr [$6D110047]
004793B8   65646961706C617965     imul    esp, fs:[ecx+$70], $6579616C
004793C1   7231                   jb      004793F4
004793C3   43                     inc     ebx
004793C4   6C                     insb
004793C5   69636B1B00889B         imul    esp, [ebx+$6B], $9B88001B
004793CC   47                     inc     edi
004793CD   001456                 add     [esi+edx*2], dl
004793D0   6F                     outsd
004793D1   6C                     insb
004793D2   756D                   jnz     00479441
004793D4   6554                   push    esp
004793D6   7261                   jb      00479439
004793D8   636B42                 arpl    [ebx+$42], bp
004793DB   61                     popa
004793DC   7243                   jb      00479421
004793DE   68616E6765             push    $65676E61
004793E3   1400                   adc     al, $00
004793E5   90                     nop
004793E6   A147000D46             mov     eax, dword ptr [$460D0047]
004793EB   6F                     outsd
004793EC   726D                   jb      0047945B
004793EE   43                     inc     ebx
004793EF   61                     popa
004793F0   6E                     outsb
004793F1   52                     push    edx
004793F2   657369                 jnb     0047945E
004793F5   7A65                   jp      0047945C
004793F7   16                     push    ss
004793F8   0090A247000F           add     [eax+$F0047A2], dl
004793FE   4F                     dec     edi
004793FF   7065                   jo      00479466
00479401   6E                     outsb
00479402   46                     inc     esi
00479403   6F                     outsd
00479404   6C                     insb
00479405   64657243               jb      0047944C
00479409   6C                     insb
0047940A   69636B180060A6         imul    esp, [ebx+$6B], $A6600018
00479411   47                     inc     edi
00479412   0011                   add     [ecx], dl
00479414   53                     push    ebx
00479415   61                     popa
00479416   7665                   jbe     0047947D
00479418   50                     push    eax
00479419   6C                     insb
0047941A   61                     popa
0047941B   796C                   jns     00479489
0047941D   697374436C6963         imul    esi, [ebx+$74], $63696C43
00479424   6B1800                 imul    ebx, [eax], $00
00479427   20A84700114F           and     [eax+$4F110047], ch
0047942D   7065                   jo      00479494
0047942F   6E                     outsb
00479430   50                     push    eax
00479431   6C                     insb
00479432   61                     popa
00479433   796C                   jns     004794A1
00479435   697374436C6963         imul    esi, [ebx+$74], $63696C43
0047943C   6B1800                 imul    ebx, [eax], $00
0047943F   40                     inc     eax
00479440   AA                     stosb
00479441   47                     inc     edi
00479442   0011                   add     [ecx], dl
00479444   4F                     dec     edi
00479445   7065                   jo      004794AC
00479447   6E                     outsb
00479448   46                     inc     esi
00479449   696C654D656E7543       imul    ebp, [ebp+$4D], $43756E65
00479451   6C                     insb
00479452   69636B1B00E8AC         imul    esp, [ebx+$6B], $ACE8001B
00479459   47                     inc     edi
0047945A   00144C                 add     [esp+ecx*2], dl
0047945D   697374426F7874         imul    esi, [ebx+$74], $74786F42
00479464   7261                   jb      004794C7
00479466   636B44                 arpl    [ebx+$44], bp
00479469   626C436C               bound   ebp, qword ptr [ebx+eax*2+$6C]
0047946D   69636B1B00C4AD         imul    esp, [ebx+$6B], $ADC4001B
00479474   47                     inc     edi
00479475   001450                 add     [eax+edx*2], dl
00479478   6C                     insb
00479479   61                     popa
0047947A   7953                   jns     004794CF
0047947C   7065                   jo      004794E3
0047947E   656442                 inc     edx
00479481   7574                   jnz     004794F7
00479483   746F                   jz      004794F4
00479485   6E                     outsb
00479486   43                     inc     ebx
00479487   6C                     insb
00479488   69636B1C00E0AD         imul    esp, [ebx+$6B], $ADE0001C
0047948F   47                     inc     edi
00479490   001550617573           add     [$73756150], dl
00479496   6553                   push    ebx
00479498   7065                   jo      004794FF
0047949A   656442                 inc     edx
0047949D   7574                   jnz     00479513
0047949F   746F                   jz      00479510
004794A1   6E                     outsb
004794A2   43                     inc     ebx
004794A3   6C                     insb
004794A4   69636B1B0000AE         imul    esp, [ebx+$6B], $AE00001B
004794AB   47                     inc     edi
004794AC   00144E                 add     [esi+ecx*2], dl
004794AF   657874                 js      00479526
004794B2   53                     push    ebx
004794B3   7065                   jo      0047951A
004794B5   656442                 inc     edx
004794B8   7574                   jnz     0047952E
004794BA   746F                   jz      0047952B
004794BC   6E                     outsb
004794BD   43                     inc     ebx
004794BE   6C                     insb
004794BF   69636B20001CAE         imul    esp, [ebx+$6B], $AE1C0020
004794C6   47                     inc     edi
004794C7   0019                   add     [ecx], bl
004794C9   50                     push    eax
004794CA   7265                   jb      00479531
004794CC   7669                   jbe     00479537
004794CE   756F                   jnz     0047953F
004794D0   7365                   jnb     00479537
004794D2   53                     push    ebx
004794D3   7065                   jo      0047953A
004794D5   656442                 inc     edx
004794D8   7574                   jnz     0047954E
004794DA   746F                   jz      0047954B
004794DC   6E                     outsb
004794DD   43                     inc     ebx
004794DE   6C                     insb
004794DF   69636B100038AE         imul    esp, [ebx+$6B], $AE380010
004794E6   47                     inc     edi
004794E7   0009                   add     [ecx], cl
004794E9   45                     inc     ebp
004794EA   7869                   js      00479555
004794EC   7443                   jz      00479531
004794EE   6C                     insb
004794EF   69636B1A0050AE         imul    esp, [ebx+$6B], $AE50001A
004794F6   47                     inc     edi
004794F7   0013                   add     [ebx], dl
004794F9   53                     push    ebx
004794FA   6F                     outsd
004794FB   756E                   jnz     0047956B
004794FD   6454                   push    esp
004794FF   7261                   jb      00479562
00479501   636B42                 arpl    [ebx+$42], bp
00479504   61                     popa
00479505   7243                   jb      0047954A
00479507   68616E6765             push    $65676E61
0047950C   1500B0AE47             adc     eax, $47AEB000
00479511   000E                   add     [esi], cl
00479513   41                     inc     ecx
00479514   6E                     outsb
00479515   696D6174696F6E         imul    ebp, [ebp+$61], $6E6F6974
0047951C   43                     inc     ebx
0047951D   6C                     insb
0047951E   69636B0E00F0AE         imul    esp, [ebx+$6B], $AEF0000E
00479525   47                     inc     edi
00479526   0007                   add     [edi], al
00479528   4E                     dec     esi
00479529   32436C                 xor     al, byte ptr [ebx+$6C]
0047952C   69636B0E00ACB0         imul    esp, [ebx+$6B], $B0AC000E
00479533   47                     inc     edi
00479534   0007                   add     [edi], al
00479536   4E                     dec     esi
00479537   33436C                 xor     eax, [ebx+$6C]
0047953A   69636B0E0034B1         imul    esp, [ebx+$6B], $B134000E
00479541   47                     inc     edi
00479542   0007                   add     [edi], al
00479544   4E                     dec     esi
00479545   3443                   xor     al, $43
00479547   6C                     insb
00479548   69636B0E007CB1         imul    esp, [ebx+$6B], $B17C000E
0047954F   47                     inc     edi
00479550   0007                   add     [edi], al
00479552   4E                     dec     esi
00479553   35436C6963             xor     eax, $63696C43
00479558   6B0E00                 imul    ecx, [esi], $00
0047955B   24B4                   and     al, $B4
0047955D   47                     inc     edi
0047955E   0007                   add     [edi], al
00479560   4E                     dec     esi
00479561   3643                   inc     ebx
00479563   6C                     insb
00479564   69636B1A008CB4         imul    esp, [ebx+$6B], $B48C001A
0047956B   47                     inc     edi
0047956C   0013                   add     [ebx], dl
0047956E   4C                     dec     esp
0047956F   697374426F7874         imul    esi, [ebx+$74], $74786F42
00479576   7261                   jb      004795D9
00479578   636B4B                 arpl    [ebx+$4B], bp
0047957B   657944                 jns     004795C2
0047957E   6F                     outsd
0047957F   776E                   jnbe    004795EF
00479581   1100                   adc     [eax], eax
00479583   94                     xchg    eax, esp
00479584   B447                   mov     ah, $47
00479586   000A                   add     [edx], cl
00479588   46                     inc     esi
00479589   6F                     outsd
0047958A   726D                   jb      004795F9
0047958C   52                     push    edx
0047958D   657369                 jnb     004795F9
00479590   7A65                   jp      004795F7
00479592   06                     push    es
00479593   54                     push    esp
00479594   46                     inc     esi
00479595   6F                     outsd
00479596   726D                   jb      00479605
00479598   310D00180D43           xor     [$430D1800], ecx
0047959E   00880A4300EC           add     [eax+$EC00430A], cl
004795A4   094600                 or      [esi+$00], eax
004795A7   44                     inc     esp
004795A8   AE                     scasb
004795A9   42                     inc     edx
004795AA   0018                   add     [eax], bl
004795AC   2D430024F5             sub     eax, $F5240043
004795B1   45                     inc     ebp
004795B2   00B48A4200C0A6         add     [edx+ecx*4+$A6C00042], dh
004795B9   44                     inc     esp
004795BA   00A8A1440078           add     [eax+$780044A1], ch
004795C0   CC                     int     3
004795C1   45                     inc     ebp
004795C2   0010                   add     [eax], dl
004795C4   304300                 xor     [ebx+$00], al
004795C7   A4                     movsb
004795C8   A944001869             test    eax, $69180044
004795CD   47                     inc     edi
004795CE   0090D4954700           add     [eax+$4795D4], dl
004795D4   07                     pop     es
004795D5   06                     push    es
004795D6   54                     push    esp
004795D7   46                     inc     esi
004795D8   6F                     outsd
004795D9   726D                   jb      00479648
004795DB   310490                 xor     [eax+edx*4], eax
004795DE   47                     inc     edi
004795DF   0038                   add     [eax], bh
004795E1   124500                 adc     al, byte ptr [ebp+$00]
004795E4   5E                     pop     esi
004795E5   000E                   add     [esi], cl
004795E7   4D                     dec     ebp
004795E8   6564696146756E6374     imul    esp, fs:[ecx+$46], $74636E75
004795F1   696F6E73000090         imul    ebp, [edi+$6E], $90000073
004795F8   FC                     cld
004795F9   95                     xchg    eax, ebp
004795FA   47                     inc     edi
004795FB   0011                   add     [ecx], dl
004795FD   022E                   add     ch, byte ptr [esi]
004795FF   330400                 xor     eax, [eax+eax]
00479602   0000                   add     [eax], al

00479604   A4                     movsb
00479605   104000                 adc     [eax+$00], al
00479608   48                     dec     eax
00479609   0000                   add     [eax], al

0047960B   00A41040000E4D         add     [eax+edx+$4D0E0040], ah
00479612   6564696146756E6374     imul    esp, fs:[ecx+$46], $74636E75
0047961B   696F6E7390558B         imul    ebp, [edi+$6E], $8B559073
00479622   EC                     in      al, dx
00479623   51                     push    ecx
00479624   53                     push    ebx
00479625   56                     push    esi
00479626   8BF2                   mov     esi, edx
00479628   8945FC                 mov     [ebp-$04], eax
0047962B   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
0047962E   E8D5B5F8FF             call    00404C08
00479633   33C0                   xor     eax, eax
00479635   55                     push    ebp

* Possible String Reference to: 'é£ªøÿëð^[Y]ÃU‹ì3ÉQQQQQSVW3ÀUh0˜G'
|
00479636   688C964700             push    $0047968C

***** TRY
|
0047963B   64FF30                 push    dword ptr fs:[eax]
0047963E   648920                 mov     fs:[eax], esp
00479641   33DB                   xor     ebx, ebx
00479643   EB01                   jmp     00479646
00479645   43                     inc     ebx

* Reference to Form1
|
00479646   A1C0EC4700             mov     eax, dword ptr [$0047ECC0]

* Reference to field Form1.OFFS_0390
|
0047964B   8B8090030000           mov     eax, [eax+$0390]
00479651   8B1498                 mov     edx, [eax+ebx*4]
00479654   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrPos;
|
00479657   E800B7F8FF             call    00404D5C
0047965C   85C0                   test    eax, eax
0047965E   74E5                   jz      00479645
00479660   8BC6                   mov     eax, esi

* Reference to Form1
|
00479662   8B15C0EC4700           mov     edx, [$0047ECC0]

* Reference to field Form1.OFFS_0390
|
00479668   8B9290030000           mov     edx, [edx+$0390]
0047966E   8B149A                 mov     edx, [edx+ebx*4]

* Reference to: System.@LStrAsg(void;void;void;void);
|
00479671   E836B1F8FF             call    004047AC
00479676   33C0                   xor     eax, eax
00479678   5A                     pop     edx
00479679   59                     pop     ecx
0047967A   59                     pop     ecx
0047967B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]ÃU‹ì3ÉQQQQQSVW3ÀUh0˜G'
|
0047967E   6893964700             push    $00479693
00479683   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00479686   E8CDB0F8FF             call    00404758
0047968B   C3                     ret

*)
end;

end.